# Generated by Django 6.0.3 on 2026-04-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_24782067', '0002_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
